export interface CustomizerItem {
  id: string
  label: string
  description: string
  icon: string
  type: 'toggle' | 'cycler' | 'action' | 'menu'
  defaultOnStrip: boolean
  binding?: 'chatOpen' | 'stageEnabled' | 'micEnabled' | 'captionOpen' | 'geminiSession'
}

export interface CustomizerGroup {
  id: string
  name: string
  description: string
  icon: string
  items: CustomizerItem[]
}

// Priority-ordered: stage first, gemini last
export const CUSTOMIZER_CATALOG: CustomizerGroup[] = [
  {
    id: 'stage-view',
    name: 'Stage View',
    description: 'Viewport interaction modes, coordinate controls, and stage display settings.',
    icon: 'i-solar:tuning-outline',
    items: [
      {
        id: 'stage',
        label: 'Actor Stage',
        description: 'Toggles rendering of the Live2D/VRM actor stage.',
        icon: 'i-solar:clapperboard-play-bold-duotone',
        type: 'toggle',
        defaultOnStrip: true,
        binding: 'stageEnabled',
      },
      {
        id: 'always-on-top',
        label: 'Always-on-Top',
        description: 'Toggles window floating status above full-screen applications.',
        icon: 'i-solar:pin-linear',
        type: 'toggle',
        defaultOnStrip: false,
      },
      {
        id: 'viewport-tactile',
        label: 'Tactile Mode',
        description: 'Pointer click triggers active pokes; character looks at mouse cursor.',
        icon: 'i-solar:magic-stick-linear',
        type: 'toggle',
        defaultOnStrip: true,
      },
      {
        id: 'viewport-drag',
        label: 'Drag Mode',
        description: 'Mouse click-and-drag moves character; hides sliders for cleanliness.',
        icon: 'i-solar:shuffle-linear',
        type: 'toggle',
        defaultOnStrip: true,
      },
      {
        id: 'viewport-positioning',
        label: 'Positioning Mode',
        description: 'Activates advanced coordinate placement sliders (X, Y, Scale).',
        icon: 'i-solar:tuning-outline',
        type: 'toggle',
        defaultOnStrip: true,
      },
      {
        id: 'viewport-orbit',
        label: 'Orbit Mode',
        description: 'Drag rotates camera viewport around VRM/3D model environments.',
        icon: 'i-solar:eye-linear',
        type: 'toggle',
        defaultOnStrip: true,
      },
      {
        id: 'viewport-cycle-modes',
        label: 'Cycle Viewport Modes',
        description: 'Cycles sequentially through the four pointer interaction modes.',
        icon: 'i-solar:refresh-linear',
        type: 'cycler',
        defaultOnStrip: false,
      },
      {
        id: 'viewport-reset-coordinates',
        label: 'Reset Coordinates',
        description: 'Instantly resets X, Y, and Scale parameters to character defaults.',
        icon: 'i-solar:restart-square-outline',
        type: 'action',
        defaultOnStrip: false,
      },
      {
        id: 'viewport-auto-hide',
        label: 'Auto Hide / Always Show',
        description: 'Toggles whether control strip / stage UI elements auto-fade.',
        icon: 'i-ph:eye-slash',
        type: 'toggle',
        defaultOnStrip: false,
      },
    ],
  },
  {
    id: 'system-window',
    name: 'System & Window',
    description: 'Window floatings, visual styling settings, and process lifecycles.',
    icon: 'i-solar:settings-linear',
    items: [
      {
        id: 'chat',
        label: 'Chat Toggle',
        description: 'Toggles visibility of the chat overlay bubble.',
        icon: 'i-solar:chat-line-linear',
        type: 'toggle',
        defaultOnStrip: true,
        binding: 'chatOpen',
      },
      {
        id: 'mic',
        label: 'Microphone Toggle',
        description: 'Toggles voice input capturing.',
        icon: 'i-solar:muted-linear',
        type: 'toggle',
        defaultOnStrip: true,
        binding: 'micEnabled',
      },
      {
        id: 'settings',
        label: 'Settings',
        description: 'Opens the main configuration settings menu pane.',
        icon: 'i-solar:settings-linear',
        type: 'action',
        defaultOnStrip: true,
      },
      {
        id: 'theme-mode',
        label: 'Theme Mode',
        description: 'Swaps light/dark application color themes.',
        icon: 'i-solar:sun-linear',
        type: 'toggle',
        defaultOnStrip: true,
      },
      {
        id: 'exit-app',
        label: 'Exit Application',
        description: 'Clean-quits and shuts down the active AIRI process cycle.',
        icon: 'i-solar:close-circle-outline',
        type: 'action',
        defaultOnStrip: true,
      },
      {
        id: 'layout',
        label: 'Customizer',
        description: 'Toggles visibility of the Control Customizer configuration window.',
        icon: 'i-solar:widget-linear',
        type: 'action',
        defaultOnStrip: true,
      },
    ],
  },
  {
    id: 'captions-layout',
    name: 'Captions',
    description: 'Subtitles layout, caption styling alignment, and attaching behaviors.',
    icon: 'i-solar:window-frame-linear',
    items: [
      {
        id: 'caption',
        label: 'Captions Toggle',
        description: 'Toggles visibility of the subtitles text overlay.',
        icon: 'i-ph:closed-captioning-duotone',
        type: 'toggle',
        defaultOnStrip: true,
        binding: 'captionOpen',
      },
      {
        id: 'caption-docking',
        label: 'Caption Docking',
        description: 'Swaps caption overlay attachment location (Top vs Bottom).',
        icon: 'i-solar:align-bottom-line-duotone',
        type: 'toggle',
        defaultOnStrip: false,
      },
      {
        id: 'caption-follow-stage',
        label: 'Caption Follow Stage',
        description: 'Toggles if the caption overlay follows Stage coordinates or stays detached.',
        icon: 'i-solar:magnet-bold-duotone',
        type: 'toggle',
        defaultOnStrip: false,
      },
      {
        id: 'caption-layout-mode',
        label: 'Caption Layout Mode',
        description: 'Cycles subtitle display layout (Standard Bubble vs Multi-line History).',
        icon: 'i-solar:window-frame-linear',
        type: 'cycler',
        defaultOnStrip: false,
      },
    ],
  },
  {
    id: 'actor-wardrobe',
    name: 'Actor & Wardrobe',
    description: 'Visual adjustments, expressions grid, clothes swapping, and models.',
    icon: 'i-solar:user-speak-outline',
    items: [
      {
        id: 'actor-characters',
        label: 'Characters',
        description: 'Swaps active character profile and loads new Live2D/VRM models.',
        icon: 'i-solar:users-group-rounded-outline',
        type: 'menu',
        defaultOnStrip: false,
      },
      {
        id: 'actor-wardrobe',
        label: 'Wardrobe (Outfits)',
        description: 'Swaps visual skins, textures, and outfit configurations.',
        icon: 'i-solar:t-shirt-outline',
        type: 'menu',
        defaultOnStrip: false,
      },
      {
        id: 'actor-expressions',
        label: 'Expressions (Facial)',
        description: 'Triggers persistent emotional facial expression overlays.',
        icon: 'i-solar:mask-happly-outline',
        type: 'menu',
        defaultOnStrip: false,
      },
      {
        id: 'actor-idle-animations',
        label: 'Animation Cycler',
        description: 'Cycles standard breathing behavior and passive animations loop.',
        icon: 'i-solar:running-2-linear',
        type: 'cycler',
        defaultOnStrip: false,
      },
      {
        id: 'actor-motions',
        label: 'Motions',
        description: 'Plays interactive movements and dynamic body action triggers.',
        icon: 'i-solar:magic-stick-3-bold-duotone',
        type: 'menu',
        defaultOnStrip: false,
      },
      {
        id: 'actor-all-emotions',
        label: 'All Emotions',
        description: 'Full list of model emotions/expressions to preview or toggle.',
        icon: 'i-solar:emoji-funny-square-linear',
        type: 'menu',
        defaultOnStrip: false,
      },
    ],
  },
  {
    id: 'ai-gemini',
    name: 'AI & Gemini',
    description: 'Generative session toggles, vision analysis parameters, and speech actions.',
    icon: 'i-solar:magic-stick-3-bold-duotone',
    items: [
      {
        id: 'gemini-session',
        label: 'Active Session',
        description: 'Connects or disconnects the active Bidi Speech WebSocket session.',
        icon: 'i-ph:sparkle',
        type: 'toggle',
        defaultOnStrip: true,
        binding: 'geminiSession',
      },
      {
        id: 'gemini-witness',
        label: 'Witness Mode (Vision)',
        description: 'Enables or disables continuous automatic screenshot captures.',
        icon: 'i-solar:camera-linear',
        type: 'toggle',
        defaultOnStrip: false,
      },
      {
        id: 'gemini-manual-capture',
        label: 'Manual Capture',
        description: 'Instantly fires a single manual visual screenshot context capture.',
        icon: 'i-solar:camera-outline',
        type: 'action',
        defaultOnStrip: false,
      },
      {
        id: 'gemini-frequency',
        label: 'Witness Pulse Rate',
        description: 'Cycles interval duration (5m, 10m, 15m) for automatic witness captures.',
        icon: 'i-solar:clock-circle-linear',
        type: 'cycler',
        defaultOnStrip: false,
      },
      {
        id: 'gemini-tts',
        label: 'TTS Output Mode',
        description: 'Swaps output stream between native Gemini audio and custom TTS pipeline.',
        icon: 'i-solar:volume-loud-linear',
        type: 'toggle',
        defaultOnStrip: false,
      },
      {
        id: 'gemini-voice',
        label: 'Voice Cycle',
        description: 'Cycles through active character text-to-speech output voices.',
        icon: 'i-solar:user-speak-linear',
        type: 'cycler',
        defaultOnStrip: false,
      },
      {
        id: 'gemini-schedule',
        label: 'Respect Schedule',
        description: 'Enables or bypasses active proactivity schedule constraints.',
        icon: 'i-solar:calendar-linear',
        type: 'toggle',
        defaultOnStrip: false,
      },
      {
        id: 'gemini-grounding',
        label: 'Grounding',
        description: 'Toggles Google Search web context injection on or off.',
        icon: 'i-solar:global-linear',
        type: 'toggle',
        defaultOnStrip: false,
      },
    ],
  },
]
